### ISSUE TITLE
compilation error about let rec in atdgen code

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter#81]
from semgrep: make config
....

2 warnings generated.
File "src/gen/lib/Tree_sitter_j.ml", lines 119-280, characters 44-1:
119 | ............................................(
120 |   Atdgen_runtime.Oj_run.write_with_adapter Json_rule_adapter.restore (
121 |     fun ob x ->
122 |       match x with
123 |         | SYMBOL x ->
...
277 |           ) ob x;
278 |           Bi_outbuf.add_char ob ']'
279 |   )
280 | )
Error: This kind of expression is not allowed as right-hand side of `let rec'
make[2]: *** [build] Error 1
make[1]: *** [build-ocaml-tree-sitter] Error 2
make: *** [build] Error 2

**Comment by aryx** [comment]
I've tried removing atdgen (opam remove atdgen) and then installing it again (opam install atdgen) but then I get:
### output ###
#     ocamlopt atdgen/src/.atdgen_emit.objs/native/atdgen_emit__Ocaml.{cmx,o} (exit 2)
# (cd _build/default && /Users/pad/.opam/4.10.0/bin/ocamlopt.opt -w -40 -w -27 -safe-string -g -I atdgen/src/.atdgen_emit.objs/byte -I atdgen/src/.atdgen_emit.objs/native -I /Users/pad/.opam/4.10.0/lib/atd -I /Users/pad/.opam/4.10.0/lib/biniou -I /Users/pad/.opam/4.10.0/lib/easy-format -I /Users/pad/.opam/4.10.0/lib/yojson -intf-suffix .ml -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_[...]
# File "atdgen/src/ocaml.ml", line 618, characters 12-24:
# 618 | let split = Re.Str.split (Re.Str.regexp " ")
#                   ^^^^^^^^^^^^
# Error: Unbound module Re



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build atdgen 2.2.1
└─ 
╶─ No changes have been performed

**Comment by aryx** [comment]
I was trying that on macOS. Might be a weird bug on my opam installation ...

**Comment by aryx** [comment]
Note that 'make setup' by default in ocaml-tree-sitter leads to the installtion of atdgen 2.2.1
maybe we need a more recent version?

**Comment by aryx** [comment]
(seems to work on my Linux machine  with 2.2.1 though)

**Comment by aryx** [comment]
ok, rm -rf ~/.opam and redid make setup and it works now ... weird.

**Comment by mjambon** [comment]
I don't know about the first bug ("This kind of expression is not allowed as right-hand side of `let rec'"). It looks like a bad version of atdgen.
The other bug (dependency on `Re`) is https://github.com/ahrefs/atd/issues/211 and should be fixed by an upgrade.
